### ISSUE TITLE
ftdv-ilb is failing in Azure ARM deployment

### ISSUE THREAD

**Issue by BoostSebastian** [CiscoDevNet/cisco-ftdv#30]
Hi.

When trying to deploy the AutoScaler FTDv för Azure via ARM I'm getting the following:
Worth mentioning is that all resources exept `ftdv-ilb` is working and can't se any difference between `ftdv-ilb` and `ftdv-elb`.

```
{
    "status": "Failed",
    "error": {
        "code": "InvalidResourceReference",
        "message": "Resource /subscriptions/08b5eae9-f8bc-418e-ab44-a4ce25959426/resourceGroups/CISCO-VIRTUALNET-RG/providers/Microsoft.Network/virtualNetworks/CISCO-VIRTUALNET referenced by resource /subscriptions/08b5eae9-f8bc-418e-ab44-a4ce25959426/resourceGroups/FirePowerDelete/providers/Microsoft.Network/loadBalancers/ftdv-ilb was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.",
        "details": [
            {
                "code": "NotFound",
                "message": "Resource /subscriptions/08b5eae9-f8bc-418e-ab44-a4ce25959426/resourceGroups/CISCO-VIRTUALNET-RG/providers/Microsoft.Network/virtualNetworks/CISCO-VIRTUALNET not found."
            }
        ]
    }
}
``` 

I'm using the `.json` at https://github.com/CiscoDevNet/cisco-ftdv/tree/master/autoscale/azure/ARM%20Template

**Comment by ganesh-patwardhan** [comment]
I am sure you are populating 'virtualNetworkRg' this variable with wrong value (its using default value)  Or you dont have Vnet  'CISCO-VIRTUALNET' in this Resource Group (even this is default value)

**Comment by BoostSebastian** [comment]
If I create all the mentioned vNets and subnets in the ARM template it is working 👍
